#!/bin/bash

# You can add this script to your path and use a cronjob to run it 

# cd into the directory that has the bot mainpy
cd ~/REPLACEME

# run the main.py I use deploy = as cronjob as default but change it to loop if you want! Just make sure to no make a cronjob to run the loop!
# I like to copy this to my /bin/ directory so I can just call it as a command
python3 ./main.py -deploy cronjob
